version: '3.8'

services:
  imovel-nexus:
    build:
      context: .
      dockerfile: Dockerfile
    image: imovel-nexus:latest
    container_name: imovel-nexus
    restart: unless-stopped
    networks:
      - traefik-public
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.imovel-nexus.rule=Host(`seu-dominio.com`)"  # Altere para seu domínio
        - "traefik.http.services.imovel-nexus.loadbalancer.server.port=80"
        - "traefik.http.routers.imovel-nexus.entrypoints=websecure"
        - "traefik.http.routers.imovel-nexus.tls=true"
        - "traefik.docker.network=traefik-public"

networks:
  traefik-public:
    external: true