version: '3.8'

services:
  imovel-nexus:
    build:
      context: .
      dockerfile: Dockerfile
    image: imovel-nexus:latest
    container_name: imovel-nexus
    restart: unless-stopped
    ports:
      - "3000:3000"
    networks:
      - imovel-network
    environment:
      - NODE_ENV=production

networks:
  imovel-network:
    driver: bridge