version: '3.8'

services:
  imovel-nexus:
    build:
      context: .
      dockerfile: Dockerfile
    image: imovel-nexus:latest
    container_name: imovel-nexus
    restart: unless-stopped
    ports:
      - "8080:80"  # Mapeia a porta 8080 do host para a porta 80 do container
    networks:
      - imovel-network

networks:
  imovel-network:
    driver: bridge