version: '3.8'

services:
  imovel-nexus:
    build:
      context: .
      dockerfile: Dockerfile
    image: imovel-nexus:latest
    container_name: imovel-nexus
    restart: unless-stopped
    ports:
      - "8080:8080"
    networks:
      - imovel-network
    environment:
      - NODE_ENV=production
      - PORT=8080
      - HOSTNAME=0.0.0.0

networks:
  imovel-network:
    driver: bridge