version: '3.8'
services:
  frontend:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: wesley-reis-app
    ports:
      - "8080:80"
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge