// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kjlipbbrbwdzqiwvrnpw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtqbGlwYmJyYndkenFpd3ZybnB3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MjI5NTkyMzMsImV4cCI6MjAzODUzNTIzM30.EkxpPDyk_GwMR7ep-kGv3Yd5-fYYROD3gkGxSDrIc6g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);